/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VersionRouteImport } from './routes/version'
import { Route as AuthenticatedCardRouteImport } from './routes/_authenticated/card'
import { Route as AuthenticatedCommissionerRouteImport } from './routes/_authenticated/commissioner'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedSeasonRouteImport } from './routes/_authenticated/season'
import { Route as AuthenticatedWeekRouteImport } from './routes/_authenticated/week'
import { Route as ApiAutopilotRouteImport } from './routes/api/autopilot'
import { Route as ApiGridRouteImport } from './routes/api/grid'
import { Route as ApiPicksRouteImport } from './routes/api/picks'
import { Route as ApiScoreRouteImport } from './routes/api/score'
import { Route as ApiUpsetRouteImport } from './routes/api/upset'
import { Route as ApiWeekRouteImport } from './routes/api/week'
import { Route as ApiPublicHooksAutopilotRouteImport } from './routes/api/public/hooks/autopilot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VersionRoute = VersionRouteImport.update({
  id: '/version',
  path: '/version',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCardRoute = AuthenticatedCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommissionerRoute =
  AuthenticatedCommissionerRouteImport.update({
    id: '/commissioner',
    path: '/commissioner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeasonRoute = AuthenticatedSeasonRouteImport.update({
  id: '/season',
  path: '/season',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWeekRoute = AuthenticatedWeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAutopilotRoute = ApiAutopilotRouteImport.update({
  id: '/api/autopilot',
  path: '/api/autopilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGridRoute = ApiGridRouteImport.update({
  id: '/api/grid',
  path: '/api/grid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPicksRoute = ApiPicksRouteImport.update({
  id: '/api/picks',
  path: '/api/picks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScoreRoute = ApiScoreRouteImport.update({
  id: '/api/score',
  path: '/api/score',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpsetRoute = ApiUpsetRouteImport.update({
  id: '/api/upset',
  path: '/api/upset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeekRoute = ApiWeekRouteImport.update({
  id: '/api/week',
  path: '/api/week',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAutopilotRoute = ApiPublicHooksAutopilotRouteImport.update({
  id: '/api/public/hooks/autopilot',
  path: '/api/public/hooks/autopilot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/healthz': typeof HealthzRoute
  '/ops': typeof OpsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/version': typeof VersionRoute
  '/card': typeof AuthenticatedCardRoute
  '/commissioner': typeof AuthenticatedCommissionerRoute
  '/live': typeof AuthenticatedLiveRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/results': typeof AuthenticatedResultsRoute
  '/season': typeof AuthenticatedSeasonRoute
  '/week': typeof AuthenticatedWeekRoute
  '/api/autopilot': typeof ApiAutopilotRoute
  '/api/grid': typeof ApiGridRoute
  '/api/picks': typeof ApiPicksRoute
  '/api/score': typeof ApiScoreRoute
  '/api/upset': typeof ApiUpsetRoute
  '/api/week': typeof ApiWeekRoute
  '/api/public/hooks/autopilot': typeof ApiPublicHooksAutopilotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/healthz': typeof HealthzRoute
  '/ops': typeof OpsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/version': typeof VersionRoute
  '/card': typeof AuthenticatedCardRoute
  '/commissioner': typeof AuthenticatedCommissionerRoute
  '/live': typeof AuthenticatedLiveRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/results': typeof AuthenticatedResultsRoute
  '/season': typeof AuthenticatedSeasonRoute
  '/week': typeof AuthenticatedWeekRoute
  '/api/autopilot': typeof ApiAutopilotRoute
  '/api/grid': typeof ApiGridRoute
  '/api/picks': typeof ApiPicksRoute
  '/api/score': typeof ApiScoreRoute
  '/api/upset': typeof ApiUpsetRoute
  '/api/week': typeof ApiWeekRoute
  '/api/public/hooks/autopilot': typeof ApiPublicHooksAutopilotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/healthz': typeof HealthzRoute
  '/ops': typeof OpsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/version': typeof VersionRoute
  '/_authenticated/card': typeof AuthenticatedCardRoute
  '/_authenticated/commissioner': typeof AuthenticatedCommissionerRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/season': typeof AuthenticatedSeasonRoute
  '/_authenticated/week': typeof AuthenticatedWeekRoute
  '/api/autopilot': typeof ApiAutopilotRoute
  '/api/grid': typeof ApiGridRoute
  '/api/picks': typeof ApiPicksRoute
  '/api/score': typeof ApiScoreRoute
  '/api/upset': typeof ApiUpsetRoute
  '/api/week': typeof ApiWeekRoute
  '/api/public/hooks/autopilot': typeof ApiPublicHooksAutopilotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/healthz'
    | '/ops'
    | '/privacy'
    | '/terms'
    | '/version'
    | '/card'
    | '/commissioner'
    | '/live'
    | '/onboarding'
    | '/results'
    | '/season'
    | '/week'
    | '/api/autopilot'
    | '/api/grid'
    | '/api/picks'
    | '/api/score'
    | '/api/upset'
    | '/api/week'
    | '/api/public/hooks/autopilot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/healthz'
    | '/ops'
    | '/privacy'
    | '/terms'
    | '/version'
    | '/card'
    | '/commissioner'
    | '/live'
    | '/onboarding'
    | '/results'
    | '/season'
    | '/week'
    | '/api/autopilot'
    | '/api/grid'
    | '/api/picks'
    | '/api/score'
    | '/api/upset'
    | '/api/week'
    | '/api/public/hooks/autopilot'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/healthz'
    | '/ops'
    | '/privacy'
    | '/terms'
    | '/version'
    | '/_authenticated/card'
    | '/_authenticated/commissioner'
    | '/_authenticated/live'
    | '/_authenticated/onboarding'
    | '/_authenticated/results'
    | '/_authenticated/season'
    | '/_authenticated/week'
    | '/api/autopilot'
    | '/api/grid'
    | '/api/picks'
    | '/api/score'
    | '/api/upset'
    | '/api/week'
    | '/api/public/hooks/autopilot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HealthzRoute: typeof HealthzRoute
  OpsRoute: typeof OpsRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  VersionRoute: typeof VersionRoute
  ApiAutopilotRoute: typeof ApiAutopilotRoute
  ApiGridRoute: typeof ApiGridRoute
  ApiPicksRoute: typeof ApiPicksRoute
  ApiScoreRoute: typeof ApiScoreRoute
  ApiUpsetRoute: typeof ApiUpsetRoute
  ApiWeekRoute: typeof ApiWeekRoute
  ApiPublicHooksAutopilotRoute: typeof ApiPublicHooksAutopilotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/version': {
      id: '/version'
      path: '/version'
      fullPath: '/version'
      preLoaderRoute: typeof VersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/card': {
      id: '/_authenticated/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof AuthenticatedCardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commissioner': {
      id: '/_authenticated/commissioner'
      path: '/commissioner'
      fullPath: '/commissioner'
      preLoaderRoute: typeof AuthenticatedCommissionerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/season': {
      id: '/_authenticated/season'
      path: '/season'
      fullPath: '/season'
      preLoaderRoute: typeof AuthenticatedSeasonRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/week': {
      id: '/_authenticated/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof AuthenticatedWeekRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/autopilot': {
      id: '/api/autopilot'
      path: '/api/autopilot'
      fullPath: '/api/autopilot'
      preLoaderRoute: typeof ApiAutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grid': {
      id: '/api/grid'
      path: '/api/grid'
      fullPath: '/api/grid'
      preLoaderRoute: typeof ApiGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/picks': {
      id: '/api/picks'
      path: '/api/picks'
      fullPath: '/api/picks'
      preLoaderRoute: typeof ApiPicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/score': {
      id: '/api/score'
      path: '/api/score'
      fullPath: '/api/score'
      preLoaderRoute: typeof ApiScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upset': {
      id: '/api/upset'
      path: '/api/upset'
      fullPath: '/api/upset'
      preLoaderRoute: typeof ApiUpsetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/week': {
      id: '/api/week'
      path: '/api/week'
      fullPath: '/api/week'
      preLoaderRoute: typeof ApiWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/autopilot': {
      id: '/api/public/hooks/autopilot'
      path: '/api/public/hooks/autopilot'
      fullPath: '/api/public/hooks/autopilot'
      preLoaderRoute: typeof ApiPublicHooksAutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCardRoute: typeof AuthenticatedCardRoute
  AuthenticatedCommissionerRoute: typeof AuthenticatedCommissionerRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedSeasonRoute: typeof AuthenticatedSeasonRoute
  AuthenticatedWeekRoute: typeof AuthenticatedWeekRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCardRoute: AuthenticatedCardRoute,
  AuthenticatedCommissionerRoute: AuthenticatedCommissionerRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedSeasonRoute: AuthenticatedSeasonRoute,
  AuthenticatedWeekRoute: AuthenticatedWeekRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HealthzRoute: HealthzRoute,
  OpsRoute: OpsRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  VersionRoute: VersionRoute,
  ApiAutopilotRoute: ApiAutopilotRoute,
  ApiGridRoute: ApiGridRoute,
  ApiPicksRoute: ApiPicksRoute,
  ApiScoreRoute: ApiScoreRoute,
  ApiUpsetRoute: ApiUpsetRoute,
  ApiWeekRoute: ApiWeekRoute,
  ApiPublicHooksAutopilotRoute: ApiPublicHooksAutopilotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
